### ISSUE TITLE
Package name great again

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/gophertelekomcloud#102]
Currently, our go sdk has name `golangsdk`
Below we have new names and we need to choose one of them:
1. `gophertelekom`
2. `gopherotc`

Feel free to add new package name here

**Comment by lego963** [comment]
`otcsdk`

**Comment by Aloento** [comment]
`otcsdk` is enough  
I personally don't like "gopher", it seems redundant.

**Comment by outcatcher** [comment]
That's lame and uncool 😸 and containing no language reference, `otcsdk` can be for any language. OTC actually have several SKDs

**Comment by Aloento** [comment]
But we don't maintain any other sdk except python and golang.
Then this is only for the package name in the golang package, which means that this package name is also only visible in golang, so I say there is no need to get too fancy.

**Comment by outcatcher** [comment]
That's my bad :) the issue is not about repository name, but go package name
