### ISSUE TITLE
Add credentials caching

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#133]
Credentials caching will be added to the `python-openstackclient`:

https://review.opendev.org/c/openstack/python-openstackclient/+/765652
https://review.opendev.org/c/openstack/openstacksdk/+/735352

This can also be added to the SDK.

**Comment by Aloento** [comment]
It seems to be about caching credentials (token, ak/sk) in the local keyring, at least it referred in RN https://review.opendev.org/c/openstack/openstacksdk/+/735352/5/releasenotes/notes/cache-auth-in-keyring-773dd5f682cd1610.yaml

Currently token stored in memory, but this allows to store it in the system keyring.
