### ISSUE TITLE
[OBS] Open Telekom Cloud - Get returns Action Forbidden

### ISSUE THREAD

**Issue by knudsenTaunus** [opentelekomcloud/gophertelekomcloud#143]
Hi,

Im trying to access a bucket in my OTC Cluster. My User has the right permissions and so, but I keep getting a 403, can anyone help me here?

This is my code:

```
func TestHandleImagesGET(t *testing.T) {
	opts := golangsdk.AuthOptions{
		IdentityEndpoint: "https://iam.eu-de.otc.t-systems.com/v3/",
		Username:         <username>,
		Password:         <password>,
		DomainName:       <domainname>}

	provider, err := openstack.AuthenticatedClient(opts)
	assert.NoError(t, err)

	endOpts := golangsdk.EndpointOpts{
		Type:   "identity",
		Region: "*"}

	obsClient, err := openstack.NewObjectStorageV1(provider, endOpts)
	assert.NoError(t, err)

	objURL := <urlToMyDocument>
	document := []byte{}

	resp, err := obsClient.Get(objURL, document, nil)
	assert.NoError(t, err)
	assert.NotNil(t, provider)
}
```

**Comment by lego963** [comment]
@knudsenTaunus I'm checking your config. What do you want to do?

UPD: I recommend using the `objectstorage` pkg instead of client `GET/POST/PUT`.

UPD2: Can you try to update your files with
```
opts := golangsdk.AuthOptions{
	IdentityEndpoint: "https://iam.eu-de.otc.t-systems.com/v3/",
	Username:         <username>,
	Password:         <password>,
	DomainName:  <domain_name>,
	TenantName:    <tenant_name>,
}

golangsdk.EndpointOpts{
		Region: <your-region>,
}
```

**Comment by knudsenTaunus** [comment]
Hey Lego, thanks for your affort, but I have a small update:

I figured out, that the AuthOptions dont work as my Service Catalof inside the token only has one service which is identity.
I updated my code to use AK/SK AuthOptions like so:


```
aksk := golangsdk.AKSKAuthOptions{
		IdentityEndpoint: "https://iam.eu-de.otc.t-systems.com/v3/",
		ProjectId:        "",
		ProjectName:      "",
		Region:           "",
		Domain:           "",
		DomainID:         "",
		AccessKey:        "",
		SecretKey:        "",
	}


	provider, err := openstack.AuthenticatedClient(aksk)
	assert.NoError(t, err)

	endOpts := golangsdk.EndpointOpts{
		Type:   "object-store",
		Region: "eu-de",
	}

	objURL := ""

	obsClient, err := openstack.NewObjectStorageV1(provider, endOpts)

	assert.NoError(t, err)
	resp, err := obsClient.Get(objURL, nil, &golangsdk.RequestOpts{})
	assert.NoError(t, err)

	log.Print(resp)

	assert.NotNil(t, provider)
```

the result is that I get a service catalog with 67 entries, which is nice. I can use the object-store then. But still I get  the same 403 error :/

**Comment by gtema** [comment]
What you describe is a typical case of difference between domain scope (identity operations) and project scope (all the rest). Only for project scope token you get the endpoints info.

I would assume you get 403 due to missing permissions. When you use OBS service you account (used for ak/SK) need to have tenant admin privilege on the "global" level (not project related). This need to be done in the Identity and Management Service. That is often the reason for 403 error (assuming you got authorized properly, otherwise you'll normally get 401).

**Comment by knudsenTaunus** [comment]
hey gtema, thanks for you reply. I also read about this and applyed the the tenant admin, still doesnt change anything

**Comment by gtema** [comment]
btw, not sure which exact code you run now, but if you get the endpoint from service catalog you should get the one with service type "object" and not "object-store". Are you able to gather logs which exact request is being sent? I feel here is the problem
