### ISSUE TITLE
[DCS] creation/update fail if more that single backup_at

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#15]
When more than 1 day is selected in `backup_at`, got 400 response:
`{"error":{"code":"111400075","message":"check backup policy param backup_at error","ext_message":null}}`

At the same time, the creation of DCS on the console doesn't show such a problem

**Comment by Aloento** [comment]
Is it possible to provide a minimum reproduction code?

**Comment by outcatcher** [comment]
I suppose, it was noticed when running [TestAccDcsInstancesV1_basic](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/5064399ed8b460f9fe0b346289e7bd41e8c85a2d/opentelekomcloud/acceptance/dcs/resource_opentelekomcloud_dcs_instance_v1_test.go#L20) TF test with different `backup_at`  value, as there is no acceptance test in the SDK for this case.

**Comment by Aloento** [comment]
We have modified the TF Provider, which should now work properly as the tests passed.
