### ISSUE TITLE
[IAM] URLs for requests 

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/gophertelekomcloud#162]
Some URLs have tricks with replacing `strings.Replace(url, "/v3/", "/v3.0/", 1)`. Correct version should be already presented in client.

**Comment by Aloento** [comment]
Artem Lifshits said:
I've done some research and in teraform this code replacement is implemented right in the client endpoint (depending on which client you are using - in our case we need domain level client with 3.0 endpoint).

**Comment by lego963** [comment]
@Aloento we have in gitlab `service-catalog` project, so you can add missing endpoints there and add new client function.

**Comment by artem-lifshits** [comment]
@lego963 @Aloento I don't see any reason to add new endpoint in service-catalog, IAM use 2 endpoints (v3.0 and v3) for different requests. Adding new entry for the same service may lead to misunderstanding and confusion.

**Comment by lego963** [comment]
I don't insist on that change, it was just a proposal. You can close the issue if you think that it's overhead.

**Comment by Aloento** [comment]
I think we should do something in the SDK so that users don't have to think about this conversion.
Because it is not excluded that someone use golang sdk directly instead of teraform.

**Comment by Aloento** [comment]
Currently we do something like this:
https://github.com/opentelekomcloud/gophertelekomcloud/blob/5617dc1705b5dd2c7ceb6d0f27ce4dca966fff7e/openstack/client.go#L607

**Comment by anton-sidelnikov** [comment]
we need total rework of gophertelekomcloud/openstack/client.go because it contains not up-to-date code, users have troubles of using our sdk, we can move clients from acceptance or other way. Will create another issue for that.
