### ISSUE TITLE
[CES] Implement missing APIs

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#188]
It seems there are two missing APIs:
- `Alarm Rule`
- `Quota Management`

**Comment by Aloento** [comment]
So can you list which APIs are missing?

**Comment by outcatcher** [comment]
Comparing documentation and sdk, there is 2 missing: `alarm rule` and `quota management`

**Comment by Aloento** [comment]
Alarm Rule Management https://docs.otc.t-systems.com/api/ces/ces_03_0026.html
Quota Management https://docs.otc.t-systems.com/api/ces/ces_03_0037.html
