### ISSUE TITLE
Tolerations & affinities in CCE add-on templates

### ISSUE THREAD

**Issue by DasLeo** [opentelekomcloud/gophertelekomcloud#220]
Since we are able to set `k8s_tags` and `taints` in CCE nodepools it would be great to have the possibility to set affinities and tolerations as well on the add-on part.
Otherwise it's impossible to schedule the add-on pods properly.

This issue is linked to:
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1224

**Comment by lego963** [comment]
Current OTC approach won't allow this setting.
