### ISSUE TITLE
[RDS] add more arguments to read replica creation and update

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#229]
Required for https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1099
Following arguments should be set:
- `security_group_id`
- `public_ips`
- `vpc_id`
- `subnet_id`

**Comment by Aloento** [comment]
I looked through the issue and api documentation and found that security_group_id; vpc_id; subnet_id all have corresponding request fields.
So which method specifically needs to be enhanced?

**Comment by Aloento** [comment]
There are APIs related to disaster recovery.
ShowDrReplicaStatus
StartInstanceDrToMasterAction
StartInstanceMasterDrAction
StartInstanceSlaveDrAction

**Comment by outcatcher** [comment]
This issue is about SDK: `CreateReplicaOpts` missing those arguments

**Comment by Aloento** [comment]
ok I see that, If I'm following the code correctly, the this is related to the CreateRestoreInstance

CreateReplicaOpts -> ToCreateReplicaMap -> CreateReplica -> CreateURL -> `POST /v3/{project_id}/instances`

**Comment by Aloento** [comment]
Except for public_ips which can't be configured, the others can, and I or whoever has time will add those fields.

**Comment by Aloento** [comment]
I am free to deal with this issue, can we communicate the details? What IM do you use? @outcatcher

**Comment by outcatcher** [comment]
I suppose, I still should have access to the OTC eco matrix :) I'm available there with same `@outcatcher` nickname.

**Comment by Aloento** [comment]
After checking the actual API, we found that these fields are not currently supported.
