### ISSUE TITLE
Authenticate not possible with token

### ISSUE THREAD

**Issue by cgroschupp** [opentelekomcloud/gophertelekomcloud#25]
It's not possible to authenticate with token. i get this error `FATA[0000] unable create net client error="No suitable endpoint could be found in the service catalog."` with gophertelekomcloud sdk.
```go
package main

import (
	"fmt"
	"os"

	golangsdk "github.com/opentelekomcloud/gophertelekomcloud"
	"github.com/opentelekomcloud/gophertelekomcloud/openstack"
	"github.com/opentelekomcloud/gophertelekomcloud/openstack/networking/v2/routes"
	"github.com/opentelekomcloud/gophertelekomcloud/pagination"
	"github.com/sirupsen/logrus"
)

func main() {
	opts := golangsdk.AuthOptions{
		IdentityEndpoint: os.Getenv("OS_AUTH_URL"),
		TokenID:          os.Getenv("OS_TOKEN"),
		DomainName:       os.Getenv("OS_DOMAIN_NAME"),
		TenantName:       os.Getenv("OS_REGION_NAME"),
	}

	provider, err := openstack.AuthenticatedClient(opts)

	if err != nil {
		logrus.WithError(err).Fatal("unable create client")
	}

	netClient, err := openstack.NewNetworkV2(provider, golangsdk.EndpointOpts{Region: os.Getenv("OS_REGION_NAME")})
	if err != nil {
		logrus.WithError(err).Fatal("unable create net client")
	}
	pager := routes.List(netClient, routes.ListOpts{})

	pager.EachPage(func(page pagination.Page) (bool, error) {
		routes, err := routes.ExtractRoutes(page)
		if err != nil {
			return false, err
		}
		fmt.Println(routes)
		return true, nil
	})
}
```

Same code with `huaweicloud` works:
```go
package main

import (
	"fmt"
	"os"

	"github.com/huaweicloud/golangsdk"
	"github.com/huaweicloud/golangsdk/openstack"
	"github.com/huaweicloud/golangsdk/openstack/networking/v2/routes"
	"github.com/huaweicloud/golangsdk/pagination"
	"github.com/sirupsen/logrus"
)

func main() {
	opts := golangsdk.AuthOptions{
		IdentityEndpoint: os.Getenv("OS_AUTH_URL"),
		TokenID:          os.Getenv("OS_TOKEN"),
		DomainName:       os.Getenv("OS_DOMAIN_NAME"),
		TenantName:       os.Getenv("OS_REGION_NAME"),
	}

	provider, err := openstack.AuthenticatedClient(opts)

	if err != nil {
		logrus.WithError(err).Fatal("unable create client")
	}

	netClient, err := openstack.NewNetworkV2(provider, golangsdk.EndpointOpts{Region: os.Getenv("OS_REGION_NAME")})
	if err != nil {
		logrus.WithError(err).Fatal("unable create net client")
	}
	pager := routes.List(netClient, routes.ListOpts{})

	pager.EachPage(func(page pagination.Page) (bool, error) {
		routes, err := routes.ExtractRoutes(page)
		if err != nil {
			return false, err
		}
		fmt.Println(routes)
		return true, nil
	})
}
```
My environment variables:
```bash
export OS_AUTH_URL=https://iam.eu-de.otc.t-systems.com/v3/
export OS_REGION_NAME=eu-de
export OS_DOMAIN_NAME=OTC-EU-DE-0000000000000000000
export OS_TOKEN=xxx
```

**Comment by lego963** [comment]
@cgroschupp I have tried to do same and I met this problem when I set `OS_REGION`. But after I set `OS_REGION_NAME` and I've received endpoint

**Comment by outcatcher** [comment]
This seems to be a problem, as 
```go
	opts := golangsdk.AuthOptions{
		IdentityEndpoint: os.Getenv("OS_AUTH_URL"),
		TokenID:          os.Getenv("OS_TOKEN"),
	}
```
Won't work with same error: `No suitable endpoint could be found in the service catalog.`
But auth URL and token ID should be perfectly enough for authentication

**Comment by cgroschupp** [comment]
I found the problem in https://github.com/opentelekomcloud/gophertelekomcloud/blob/37ff2b5e2da821f330b01c64369e770fe46f29d1/openstack/client.go#L165-L170

This was add in https://github.com/opentelekomcloud/gophertelekomcloud/pull/12

When `AuthTokenID` exists, the `/v3/auth/tokens` request contains no json payload, only the header`X-Subject-Token` and `X-Auth-Token` are set. What results in response without service catalog.

If `AuthTokenID' exists, the request `/v3/auth/tokens' does not contain a jsonpayload, only the header `X-Subject-Token' and `X-Auth-Token' are set.  Which results in a response without service catalog.

@outcatcher Do you know why not every auth request uses `tokens3.Create`?

**Comment by outcatcher** [comment]
@cgroschupp `result = tokens3.Get(v3Client, opts.AuthTokenID())` is there exactly for getting service catalog.
For project-scoped token, it should provide a service catalog in the response:
https://docs.otc.t-systems.com/en-us/api/iam/en-us_topic_0057845585.html

**Comment by outcatcher** [comment]
@cgroschupp 
Currently, I'm not able to reproduce the issue with your [code](https://github.com/opentelekomcloud/gophertelekomcloud/issues/25#issue-732256574)
```bash
$ env | grep OS_
OS_TOKEN=MIIFbAYJKoZIhvc...
OS_AUTH_URL=https://iam.eu-de.otc.t-systems.com/v3/
OS_DOMAIN_NAME=OTC00000000001000000448
OS_REGION_NAME=eu-de
$ go run main/main.go

$ echo $?
0
```

Are you able to reproduce it on the latest `master`?

**Comment by cgroschupp** [comment]
I have found my problem, I have created my token incorrectly. thanks a lot for the help.
