### ISSUE TITLE
Style: `Builder` interface is redundant

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#274]
In most cases `<Smth>Builder` interface has only one implementation, so this seems to be redundant in this case.

Pros in having interfaces:
1. Other implementations can be used
2. No implementation details available for the consumer (seems useless, as a consumer is declared in the same place)
5. `nil` value is always correct input
3. Can be mocked in tests (not used)
4. Already in style guide

Cons in having interfaces:
1. More code
2. More public members in the package

**Comment by lego963** [comment]
We can't do it right now, because we use `ValueSpecs` to extend struct

**Comment by Aloento** [comment]
If you know the Entity Framework, you can also find many interfaces with only one global implementation.

**Comment by outcatcher** [comment]
Not my problem anymore, but if you see someone using some approach, it doesn't matter it fits your cases — every approach has pros and cons, it's common to select approach fitting your needs 🤷‍♂️

**Comment by Aloento** [comment]
@outcatcher For me personally, I define their interfaces before I implement the functions and then do next.

**Comment by outcatcher** [comment]
I suppose both approaches are generally okay (though I personally prefer the simplest/with the least code). So that was a question if another way can be adopted — to be discussed whenever it should be closed or added to a backlog as a future plan.

**Comment by Aloento** [comment]
According to the discussion, we consider it redundant so it will be gradually cleaned up.
