### ISSUE TITLE
Proposal: Add pointer converter functions

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#294]
Add pointer-to-value and value-to-pointer converting functions same as in [AWS SDK](https://github.com/aws/aws-sdk-go/blob/main/aws/convert_types.go)

**Comment by Aloento** [comment]
What benefits can we gain from these methods?

**Comment by lego963** [comment]
@Aloento sometime we use ptr values in `CreateOpts/UpdateOpts`, that is why we want to have a simple call `ValueToPtr(<some value>)`, instead of 
```go
value := <some value>
createOpts := pkgs.CreateOpts{
  value: &value
}
```

**Comment by Aloento** [comment]
According to the discussion, I will implement this feature.

**Comment by Aloento** [comment]
I found this
https://github.com/opentelekomcloud/gophertelekomcloud/blob/89bf5c80d0bbd5dad9ed2aaf08282363750813c3/params.go#L199
