### ISSUE TITLE
Testing: get rid of `defer` statements in tests

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#306]
We should use `t.Cleanup()` instead.

`defer` is not guaranteed to be run, as `t.Fatal` runs `runtime.Goexit()`

**Comment by Aloento** [comment]
Agree, there is still a big difference between defer and C#'s using and Java's try-with-resources.

**Comment by outcatcher** [comment]
`defer` is super-duper cool thing costing nearly nothing and AFAIK just placing a method call before (or it this called *after* in this case? 😄) function `return` in execution stack (not so much stack after that), but there is a big difference because failing tests literally [end goroutine](https://pkg.go.dev/testing#T.FailNow), not returning from `t.Fatal` call. I suppose, there is some reason for that, like guaranteed exit on timeout and smth like that, but it's counterintuitive. So only guaranteed things to execute are functions added with `t.Cleanup`.

In terms of Java it's equal to ~shooting in face~ calling `System.exit` but limited to test goroutine (and every Go test spawns own goroutine).

**Comment by Aloento** [comment]
I think it's worth spending a little overhead to keep memory safe as C# does. At least it will perform as you see it.

**Comment by Aloento** [comment]
According to the discussion, we will gradually change the existing cleanup operation to `t.Cleanup`

**Comment by anton-sidelnikov** [comment]
Think we can close this, seems all defer func substituted by t.Cleanup now
