### ISSUE TITLE
[RDS] Restart issue

### ISSUE THREAD

**Issue by eumel8** [opentelekomcloud/gophertelekomcloud#342]
I try to use [RDS V3 Restart function](https://github.com/opentelekomcloud/gophertelekomcloud/blob/devel/openstack/rds/v3/instances/requests.go#L160) with the following call:
```
restart, err := instances.Restart(client, instances.RestartRdsInstanceOpts{Restart: "{}"}, rds.Id).Extract()
```
which is also provided in [acceptance test](https://github.com/opentelekomcloud/gophertelekomcloud/blob/devel/acceptance/openstack/rds/v3/rds_test.go#L41) and [Terraform provider](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/opentelekomcloud/services/rds/resource_opentelekomcloud_rds_instance_v3.go#L558)

In any case the generated API call is

```` json
{"restart": "{}"}
````
which caused a Server failure with error 500. Regarding [documentation](https://docs.otc.t-systems.com/api/rds/rds_06_0003.html) the expected body is

```` json
{"restart": {}}
````

So, it seems [string](https://github.com/opentelekomcloud/gophertelekomcloud/blob/devel/openstack/rds/v3/instances/requests.go#L145) is the wrong data type

**Comment by vladimirvshivkov** [comment]
@eumel8 
Thanks for your feedback!

Just checked, instance restart works fine.

Acceptance test passed:
```=== RUN   TestRdsLifecycle
    helpers.go:16: Attempting to create RDSv3
    helpers.go:62: Created RDSv3: eb7f0c9cd37f49bc9e0e5da509388975in03
    helpers.go:77: Attempting to increase volume size
    helpers.go:79: Update volume size could be done only in status `available`
    helpers.go:96: RDSv3 successfully updated: eb7f0c9cd37f49bc9e0e5da509388975in03
    tools.go:72: {
          "id": "eb7f0c9cd37f49bc9e0e5da509388975in03",
          "name": "rds-TqHS6B4I",
          "status": "BUILD",
          "datastore": {
            "type": "PostgreSQL",
            "version": "11"
          },
          "ha": {
            "mode": ""
          },
          "configuration_id": "",
          "port": "8635",
          "backup_strategy": {
            "start_time": "02:00-03:00",
            "keep_days": 7
          },
          "enterprise_project_id": "",
          "disk_encryption_id": "",
          "flavor_ref": "rds.pg.c2.medium",
          "volume": {
            "type": "COMMON",
            "size": 100
          },
          "region": "eu-de",
          "availability_zone": "eu-de-01",
          "vpc_id": "9bd20f92-a28e-4ddf-98d4-afe6b507619f",
          "subnet_id": "476f4e2b-baf1-4e85-9809-44944ea736e9",
          "security_group_id": "cdfde235-5c6b-46b2-80ba-19f87c8cc47d",
          "charge_info": {
            "charge_mode": "postPaid"
          }
        }
    helpers.go:68: Attempting to delete RDSv3: eb7f0c9cd37f49bc9e0e5da509388975in03
    helpers.go:73: RDSv3 instance deleted: eb7f0c9cd37f49bc9e0e5da509388975in03
--- PASS: TestRdsLifecycle (471.25s)
PASS

Process finished with the exit code 0
```

<img width="896" alt="image" src="https://user-images.githubusercontent.com/32225815/164406790-c11e73c6-08cb-49fc-8ae7-44dfd5990565.png">



Please, provide logs or any other data to investigate this issue. 

Best regards!

**Comment by outcatcher** [comment]
@eumel8 I would additionally check if the instance has finished creating or whatever action is done to it just before the restart. In the acceptance tests we create an instance, wait for creation job to end, and then restart this instance.

**Comment by vladimirvshivkov** [comment]
@eumel8 We suppose the problem might appear while using an internal VPN. 
Try to run query while not connected.

**Comment by eumel8** [comment]
@vladimirvshivkov Yeah, thanks for the screenshot. I was performing the acceptance test and saw not output on the restart test. But it's doing there.

I copied the code more or less in my use case

```           
                fmt.Println("doing restart")
                restartResult, err := instances.Restart(client, instances.RestartRdsInstanceOpts{Restart: "{}"}, newRds.Status.Id).Extract()
                if err != nil {
                        err := fmt.Errorf("error rebooting rds: %v", err)
                        return err
                }
                if err := instances.WaitForJobCompleted(client, int(1800), restartResult.JobId); err != nil {
                        err := fmt.Errorf("error getting rds restart job: %v", err)
                        return err
                }
```

all what I got is from API:

```
2022/04/21 10:02:14 [DEBUG] OpenStack Request URL: POST https://rds.eu-de.otc.t-systems.com/v3/xxxxxxxxxxx/instances/59ce9eca5ef543e2a643fea393b2cfbcin01/action
2022/04/21 10:02:14 [DEBUG] OpenStack Request Headers:
Accept: application/json
Content-Type: application/json
User-Agent: golangsdk/2.0.0
X-Auth-Token: ***
2022/04/21 10:02:14 [DEBUG] OpenStack Request Body: {
  "restart": "{}"
}
2022/04/21 10:02:14 [DEBUG] OpenStack Response Code: 500
2022/04/21 10:02:14 [DEBUG] OpenStack Response Headers:
Cache-Control: no-cache, no-store, must-revalidate
Content-Length: 55
Content-Type: application/json
Date: Thu, 21 Apr 2022 10:02:14 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Server: Web Server
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Trace-Id: df16e310-b0e7-4ae0-882f-7a84646de5ed
X-Xss-Protection: 1; mode=block
2022/04/21 10:02:14 [DEBUG] OpenStack Response Body: {
  "error_code": "RDS.0005",
  "error_msg": "Server failure."
}
```

@outcatcher Yes, inctance is finished installed and status ACTIVE

**Comment by eumel8** [comment]
@vladimirvshivkov @outcatcher 
 very strange. 
I scaled up the acceptance test to a HA instance and from Postgres to MySQL (but that's irrelevant):

```
--- a/acceptance/openstack/rds/v3/helpers.go
+++ b/acceptance/openstack/rds/v3/helpers.go
@@ -34,21 +34,24 @@ func createRDS(t *testing.T, client *golangsdk.ServiceClient, region string) *in
                Name:             rdsName,
                Port:             "8635",
                Password:         "acc-test-password1!",
-               FlavorRef:        "rds.pg.c2.medium",
+               FlavorRef:        "rds.mysql.c2.medium.ha",
                Region:           region,
-               AvailabilityZone: az,
+               AvailabilityZone: "eu-de-01,eu-de-03",
                VpcId:            vpcID,
                SubnetId:         subnetID,
                SecurityGroupId:  openstack.DefaultSecurityGroup(t),
                DiskEncryptionId: kmsID,
-
+                Ha: &instances.Ha{
+                        Mode:            "Ha",
+                        ReplicationMode: "semisync",
+                },
                Volume: &instances.Volume{
                        Type: "COMMON",
                        Size: 100,
                },
                Datastore: &instances.Datastore{
-                       Type:    "PostgreSQL",
-                       Version: "11",
+                       Type:    "MySQL",
+                       Version: "8",
                },
        }
```
and the restart failed with 

```
2022/04/21 14:15:40 [DEBUG] OpenStack Response Body: {
  "error_code": "RDS.0005",
  "error_msg": "Server failure."
}
```
So, there is a difference in single instance restart and ha instances. In the V1 API we had the differences in InstanceID and NodeID, which are different to handle, e.g. in restart procedure.

In this case it seems workable `"restart": {}` but this needs a type change as mentioned before. Or are there other tricks to remove the "" from the request?

**Comment by outcatcher** [comment]
No, this will require a type change in the request opts.
This can either be fixed changing `RestartRdsInstanceOpts.Restart` type or using another type matching `RestartRdsInstanceBuilder` interface (as a temporary solution), e.g. smth like:
```go
type myRestartRDSOpts struct {
	Restart struct{} `json:"restart"`
}

func (opts myRestartRDSOpts) ToRestartRdsInstanceMap() (map[string]interface{}, error) {
	b, err := golangsdk.BuildRequestBody(&opts, "")
	if err != nil {
		return nil, err
	}
	return b, nil
}
``` 
And then passing this structure to `Restart` call:
```go
restart, err := instances.Restart(client, myRestartRDSOpts{}, rds.Id).Extract()
```

Currently I see in doc that `restart` is an empty JSON object, but if I'm remembering right, previously it was mentioned as a string.

**Comment by eumel8** [comment]
@outcatcher Yeah, too bad it's working on a single instance. Spent a day to found out what happened.
Thanks for the code snippet, works now as expected!

**Comment by outcatcher** [comment]
@eumel8 Thanks for your investigation! That's a 99% of the fix. We should add this case to our acceptance tests :slightly_smiling_face:

**Comment by eumel8** [comment]
Sorry, that I bother that 1% untested code ;-)
