### ISSUE TITLE
[CES] Alarm Rule suppress_duration is missing

### ISSUE THREAD

**Issue by eumel8** [opentelekomcloud/gophertelekomcloud#349]
While setup alarm rules in CES it's possible to setup when the alarm should repeat (once or specific time period). Tha value is not described in API doc and only setup via UI.
Possibly ConditionOpts can extend with this parameter:

```golang
type ConditionOpts struct {
	Period             int    `json:"period" required:"true"`
	SuppressDuration   int    `json:"suppress_duration"`
	Filter             string `json:"filter" required:"true"`
	ComparisonOperator string `json:"comparison_operator" required:"true"`
	// The Value ranges from 0 to MAX_VALUE
	Value int    `json:"value"`
	Unit  string `json:"unit,omitempty"`
	Count int    `json:"count" required:"true"`
}
```

Due the missing documentation it might be an `int`  and it seems not required (default is once). Not sure what I missed here, so applied this issue :-)

**Comment by lego963** [comment]
@eumel8 we can try to add this field, but doc in hc should be fixed
PS:
I've opened too many tickets in CES, but NOBODY cares.

**Comment by eumel8** [comment]
@lego963 I tested SuppressDuration and it works than expected. The alarm will repeat after x seconds

i.e.
```golang
---    
            Condition: alarmrule.ConditionOpts{
                        Period:             300,
                        SuppressDuration:   600,
                        Filter:             "average",
                        ComparisonOperator: ">=",
                        Value:              90,
                        Unit:               "",
                        Count:              3,
                },
---
```

Please merge if it's okay for you and make a new release to get this fixes live.

For documentation issue I heard some updates are planned, maybe @Nils-Magnus has more information
