### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by eumel8** [opentelekomcloud/gophertelekomcloud#357]
Please publish a new release to get the latest fixes, thx!

**Comment by vladimirvshivkov** [comment]
done

**Comment by lego963** [comment]
@eumel8 but it's not required to wait for a release. If you want to use `devel` branch do the following commands
```sh
go get github.com/opentelekomcloud/gophertelekomcloud@devel
go mod tidy
```

**Comment by eumel8** [comment]
@lego963 thanks for the hint, but I'm nearly done with my RDS Operator. And I want to put all things together, before I present the results on a conference in 2 weeks here in Berlin.

**Comment by gtema** [comment]
@eumel8 are you playing into the direction of https://crossplane.io/?

**Comment by eumel8** [comment]
@gtema Saw this on KubeCon but I'm going currently not in this direction.
