### ISSUE TITLE
[CBR]: Add tag management for vaults

### ISSUE THREAD

**Issue by artem-lifshits** [opentelekomcloud/gophertelekomcloud#370]
Tags management API for CBR vault is implemented in OTC.

Please add this functionality for gophertelekomcloud.

The API that needs to be implemented:
Batch adding of tags
Batch deleting of tags
Query tags of an associated resource

**Comment by Aloento** [comment]
Related issue: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1598
Internal: https://jira.tsi-dev.otc-service.com/browse/DM-3663

**Comment by Aloento** [comment]
@vladimirvshivkov could you issue the new version of the SDK?

**Comment by Aloento** [comment]
Some of the code is redundant and needs to be rewritten.
