### ISSUE TITLE
Style: `Extract` is redundant

### ISSUE THREAD

**Issue by Aloento** [opentelekomcloud/gophertelekomcloud#389]
According to the results of yesterday's discussion, we will merge the `Extract` operation into the main method call.

**Comment by outcatcher** [comment]
Contribution guide should be update accordingly in #390

**Comment by Aloento** [comment]
@outcatcher This is not all documentation-related issues; this issue also includes longer-cycle refactoring tasks.

**Comment by outcatcher** [comment]
But it also includes documentation. In most cases labels are used (at least, were used) in "including smth" way. As it includes documentation changes too, in can be marked with that label :slightly_smiling_face:

**Comment by outcatcher** [comment]
Extract methods should be replaced: `ExtractIntoSlicePtr` and `ExtractIntoStructPtr` should be make functions.
I would suggest to do that _before_ merging of #381 #384. Other way you have to use workarounds.

**Comment by Aloento** [comment]
@outcatcher 
This is not realistic at the moment, as the methods related to ExtractInto are all under the Result structure.
My idea is to do the first round of refactoring and remove Extract. After that, we will do a second round of refactoring to remove the Result structure completely.

If we want to do this task in one go, then we have to do another independent branch. This will seriously delay the release.
Using progressive, it is also possible to make simultaneous changes to the TF Provider at the same time.

**Comment by anton-sidelnikov** [comment]
Done
