### ISSUE TITLE
Testing: missing acceptance tests

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#405]
There are several services missing acceptance tests.
Among them:
- [ ] Anti-DDoS
- [ ] BMS
- [ ] EVS (blockstorage)
...

Those tests should be added, at least one workflow test for each testable resource.

When you find some service you're working on missing acceptance tests, please add it to the list.

**Comment by anton-sidelnikov** [comment]
Done while refactoring
