### ISSUE TITLE
Refactor: documentation

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#406]
Packages documentation is outdated and should be moved to stand-alone document structure, as there is for the [provider](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud) or updated: this to be discussed.

Generally, it can be removed during refactoring process. I would assume that having no documentation is better than having obsolete misguiding one.

Is it okay? @anton-sidelnikov @artem-lifshits

**Comment by anton-sidelnikov** [comment]
I'm thinking that we shouldn't remove documentation during refactoring, we should start to create this stand-alone docs for each refactored service inside refactoring PR's. Or we never do this, nobody want's to write documentation. @outcatcher @Aloento @artem-lifshits

**Comment by outcatcher** [comment]
But documentation is not really a part of refactoring?

**Comment by artem-lifshits** [comment]
Readme should be enough :)
