### ISSUE TITLE
Refactor: move extract functions to `io.ReadCloser` or `io.Reader` 

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#408]
Currently `body` argument has too wide type `interface{}`, is should be changed to `io.Reader` or `io.ReadCloser` to simplify extract usage

**Comment by Aloento** [comment]
io.ReadCloser

**Comment by outcatcher** [comment]
If you're okay, I will do it :) I assume, it will take some time though.
