### ISSUE TITLE
[NEW] Data Replication Service

### ISSUE THREAD

**Issue by Aloento** [opentelekomcloud/gophertelekomcloud#446]
https://docs.otc.t-systems.com/data-replication-service/api-ref/api/index.html

part of https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1805

**Comment by eduardOrthopy** [comment]
Hi there,

September 2022 is a bit long in the tooth :)

Any word on when this might get merged/resolved?
Any assistance I can give?

**Comment by Aloento** [comment]
@eduardOrthopy Hi, sorry for the long waiting. I need to check if it's already deployed in the official env (it seems to be) and then I'll do it as soon as possible. The main functions are finished and, I need to test them.
