### ISSUE TITLE
[KMS] Implement Encrypt/Decrypt Data

### ISSUE THREAD

**Issue by keviiin38** [opentelekomcloud/gophertelekomcloud#524]
Hello,

I want to implement an application that uses Open Telekom Cloud KMS service in order to encrypt and decrypt some data.

As I saw on HuaweiCloud for example (_that uses OpenStack under the hood as well_) they have a `POST /v1.0/{project_id}/kms/encrypt-data` endpoint that allow to input plain text data and get the cipher text version in response. _Same for the decryption process._

Tell me if I'm wrong, but I didn't find any occurrence of this API endpoint or this feature in the gophertelekom SDK.

Thanks

**Comment by artem-lifshits** [comment]
Hello @keviiin38 you're right, this feature is not implemented yet.

Found no documentation on OTC side, ticket to update opened: https://jira.tsi-dev.otc-service.com/browse/OTCSEC-4935.

Feel free to work on this feature but keep in mind that we will be able to merge it only when we have documentation updated and it may take some time.

**Comment by keviiin38** [comment]
Hello @artem-lifshits, any news on this feature ? 
_As I don't have an account on Jira to see if there are some updates on the ticket._
Thanks

**Comment by artem-lifshits** [comment]
Hello @keviiin38 encryption is available in latest release.
