### ISSUE TITLE
[IAM]: Temporary Access Token duration-seconds vs duration_seconds

### ISSUE THREAD

**Issue by zeljkobekcic** [opentelekomcloud/gophertelekomcloud#568]
Hello,

I saw that the SDK in the current state passes the wrong argument to the endpoint for creating a temporary AK/SK. Right now it sends `duration-seconds` but `duration_seconds` is expected. Therefore every time an AK/SK pair with 15min validity is created and the passed duration is not respected.

Relevant code:

https://github.com/opentelekomcloud/gophertelekomcloud/blob/devel/openstack/identity/v3/credentials/requests.go#L171

Relevant documentation:

https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/access_key_management/obtaining_a_temporary_ak_sk.html

**Comment by anton-sidelnikov** [comment]
Done
