### ISSUE TITLE
[DCS/CES]: No datapoints when obtaining metrics

### ISSUE THREAD

**Issue by zeljkobekcic** [opentelekomcloud/gophertelekomcloud#573]
I am trying to obtain the metrics of DCS from the CES. Problem is that I get empty datapoints when using the `gophertelekomcloud` library. But when using a simple curl command which has been constructed with the parameters obtained from the debugger in the application trying to obtain the metrics I do get a request.

Before pulling the metrics via CES I waited to see some metrics in the dashboard.

So far I verified:

- The unmarshalling seems not to cause this issue as the raw bytes (stringified) show that the datapoints in the response are empty
- The request seems to be correct. I can curl it and get the expected data

Thank you for your help!

**Comment by anton-sidelnikov** [comment]
Not an SDK issue, please ask responsible team (orchestration?)
