### ISSUE TITLE
HTTP DELETE Method on bucket policies not allowed

### ISSUE THREAD

**Issue by Jaybee18** [opentelekomcloud/gophertelekomcloud#594]
When calling the DeleteBucketPolicy Method on an OBS client, the response is a 405 MethodNotAllowed error.

Here is a minimal example for reproduction:
```go
package main

import (
	"fmt"
	"os"

	golangsdk "github.com/opentelekomcloud/gophertelekomcloud"
	"github.com/opentelekomcloud/gophertelekomcloud/acceptance/clients"
	"github.com/opentelekomcloud/gophertelekomcloud/openstack"
	"github.com/opentelekomcloud/gophertelekomcloud/openstack/obs"
)

func GetOBSClient() (*obs.ObsClient, error) {
	os.Setenv("OS_ACCESS_KEY", "ACCESSKEY")
	os.Setenv("OS_AUTH_URL", "https://iam.eu-de.otc.t-systems.com:443/v3")
	os.Setenv("OS_PROJECT_NAME", "PROJECTNAME")
	os.Setenv("OS_REGION", "eu-de")
	os.Setenv("OS_SECRET_KEY", "SECRETKEY")
	obsClient, err := clients.NewOBSClient()
	return obsClient, err
}

func main() {
	client, err := GetOBSClient()
	if err != nil {
		fmt.Println(err)
		return
	}

	bucketName := "my-test-bucket"

	_, err = client.CreateBucket(&obs.CreateBucketInput{
		Bucket: bucketName,
	})
	if err != nil {
		fmt.Println(err)
		return
	}

	_, err = client.HeadBucket(bucketName)
	if err != nil {
		fmt.Println(err)
		return
	}

	_, err = client.SetBucketPolicy(&obs.SetBucketPolicyInput{
		Bucket: bucketName,
		Policy: `{
			"Statement": [
				{
					"Effect": "Deny",
					"Principal":{
						"ID":[
							"domain/DOMAIN_ID"
						]
					},
					"Action":[
						"GetObject"
					],
					"Resource":[
						"` + bucketName + `/*"
					]
				}
			]
		}`,
	})
	if err != nil {
		fmt.Println(err)
		return
	}

	_, err = client.DeleteBucketPolicy(bucketName)
	if err != nil {
		fmt.Println("DeleteBucketPolicyError: " + err.Error())
		return
	}
}

```

The output of this code snippet is:
```
DeleteBucketPolicyError: obs: service returned error: Status=405 Method Not Allowed, Code=MethodNotAllowed, Message=The specified method is not allowed against this resource., RequestId=0000018C3992FEBC44212EA8FE01975E
```

**Comment by artem-lifshits** [comment]
Hello @Jaybee18 `SetBucketPolicy` overwrites all the policies you already have. If you want to add new policy you have to specify new statements with the ones you already have in the bucket.

**Comment by Jaybee18** [comment]
Hello, @artem-lifshits thanks for the quick reply, but I want to remove all bucket policies that are currently attached to the bucket. And that doesn't seem to work by passing an empty string to `SetBucketPolicy`, so I tried to use `DeleteBucketPolicy`. But that gives the error I posted.

**Comment by artem-lifshits** [comment]
@Jaybee18 I've tried running the code you posted and it worked for me without errors.
That's my guess but maybe you're lacking some IAM policies? The one that you need for deletion is this one:
```
{
    "Version": "1.1",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "obs:bucket:DeleteBucketPolicy"
            ]
        }
    ]
}
```

**Comment by Jaybee18** [comment]
There was a bit of confusion with the policies right now. For some reason more than half of our policies did not get displayed when we were in the "New Edition" of the OTC Console. When we switched back to the "Old Edition" we could see that there was an additional policy that denied the deletion of bucket policies. (We already wrote an Email regarding this issue)

One other thing though: shouldn't this HTTP request return 403 instead of 405? Since the user didn't have permissions, but in general a DELETE request on bucket policies is possible.

**Comment by artem-lifshits** [comment]
I guess it's the way to differentiate between IAM and OBS policies restrictions.
IAM policies restrict request on a wider(global) level while OBS one receives the request but declines digesting it.

**Comment by Jaybee18** [comment]
To be honest, I don't quite understand what you want to tell me with that. 
I can only tell you that as a user I found that a bit misleading.

**Comment by artem-lifshits** [comment]
You were asking whether HTTP request should return 403 instead of 405 and I gave you my guess why this happens.
If you think that this behaviour is not valid feel free to open OTC support ticket,

Cheers.
