### ISSUE TITLE
Using limit and offset in SWR repositories.ListTags

### ISSUE THREAD

**Issue by dombisza** [opentelekomcloud/gophertelekomcloud#611]
Hello there,
I am having troubles with `repositories.ListTags` when I am trying to use either `Limit` or `Offset`.
It seems like both need to be defined to be able to build the correct URL query for listing.

### Defining (non-zero) `Limit`:
```go
func imageSortTags(namespace, repoName, order string, limit int) {
	opts := repositories.ListTagsOpts{
		Namespace:   namespace,
		Repository:  repoName,
		Limit:       500,
		OrderColumn: "updated_at",
		OrderType:   order,
		Offset:      0,
	}
	processTags(opts)
}
```
Error:
`ERROR: Bad request with: [GET https://swr-api.eu-de.otc.t-systems.com/v2/manage/namespaces/sdombi-container/repos/debian/tags?limit=500&order_column=updated_at&order_type=desc], error message: {"errors":[{"errorCode":"SVCSTG.SWR.4001072","errorMessage":"Web Bad request error: param offset error","detail":"Invalid parameter in filter"}]}`

### Defining (non-zero) `Offset`
```go
func imageSortTags(namespace, repoName, order string, limit int) {
	opts := repositories.ListTagsOpts{
		Namespace:   namespace,
		Repository:  repoName,
		Limit:       0,
		OrderColumn: "updated_at",
		OrderType:   order,
		Offset:      1,
	}
	processTags(opts)
}
```
Error:
`ERROR: Bad request with: [GET https://swr-api.eu-de.otc.t-systems.com/v2/manage/namespaces/sdombi-container/repos/debian/tags?offset=1&order_column=updated_at&order_type=desc], error message: {"errors":[{"errorCode":"SVCSTG.SWR.4001070","errorMessage":"Web Bad request error: param limit error","detail":"Invalid parameter in filter"}]}`

### Defining (non-zero) `Limit` and `Offset`
```go
func imageSortTags(namespace, repoName, order string, limit int) {
	opts := repositories.ListTagsOpts{
		Namespace:   namespace,
		Repository:  repoName,
		Limit:       500,
		OrderColumn: "updated_at",
		OrderType:   order,
		Offset:      1,
	}
	processTags(opts)
}
```
No errors, but then I cannot get the first element.

Can you please help me figure out how to build the `ListTagsOpts` to lets say get the oldest 10 image? Am I doing something wrong here?
```go
func processTags(opts repositories.ListTagsOpts) {
	c := createSWRClient()
	r, err := repositories.ListTags(c, opts)
	if err != nil {
		panic(err)
	}
	if len(r) == 0 {
		log.Printf("No tags exist for the repository")
	} else {
		fmt.Printf(structToJSON(r))
	}
}


```

Thanks in advance!

**Comment by anton-sidelnikov** [comment]
HI @dombisza, sorry but this is API issue, did you try with -1 for offset?

**Comment by dombisza** [comment]
@anton-sidelnikov I am not quite sure if this is an API issue. I think the API expects both `limit` and `offset` to be present in the query and the sdk does not include the one which is set to `0`.

### only defining `limit` -> FAILS
```bash
curl -H "Content-Type: application/json" -H "X-Auth-Token: $token" "https://swr-api.eu-de.otc.t-systems.com/v2/manage/namespaces/sdombi-container/repos/debian/tags?limit=500"
{"errors":[{"errorCode":"SVCSTG.SWR.4001072","errorMessage":"Web Bad request error: param offset error","detail":"Invalid parameter in filter"}]}
```

### defining both -> SUCCESS
```bash
curl -H "Content-Type: application/json" -H "X-Auth-Token: $token" "https://swr-api.eu-de.otc.t-systems.com/v2/manage/namespaces/sdombi-container/repos/debian/tags?limit=500&offset=0" 2>/dev/null |jq '.[].id
'
1141450
```

### using `-1` as `offset` -> FAILS

```bash
curl -H "Content-Type: application/json" -H "X-Auth-Token: $token" "https://swr-api.eu-de.otc.t-systems.com/v2/manage/namespaces/sdombi-container/repos/debian/tags?limit=500&offset=-1"
{"errors":[{"errorCode":"SVCSTG.SWR.4001072","errorMessage":"Web Bad request error: param offset error","detail":"Invalid parameter in filter"}]}
```

**Comment by anton-sidelnikov** [comment]
Hello @dombisza, please try now, but use pointer for offset now

**Comment by dombisza** [comment]
@anton-sidelnikov thank you, that worked!
