### ISSUE TITLE
Empty TraceStatus for traces.Traces

### ISSUE THREAD

**Issue by akyriako** [opentelekomcloud/gophertelekomcloud#631]
**Package encountered the issue:** 
github.com/opentelekomcloud/gophertelekomcloud/openstack/cts/v2/traces

**Description:**
The `TraceStatus` field of the `traces.Traces` struct is always an _empty_ string when someone collects `traces.ListTracesResponse ` using the CTSV2 client.

**Expected behavior:**
TraceStatus should be populated with the value that the user can see in Cloud Trace Service/Trace List panel in OTC Web Console

**Reference code:** 
https://github.com/akyriako/cloudtrace-exporter/blob/main/pkg/adapter/querier.go, method `getTraces`
https://github.com/akyriako/cloudtrace-exporter/blob/main/pkg/adapter/adapter.go, method `GetEvents`

**Comment by artem-lifshits** [comment]
Hello @akyriako I've fixed the issue please check latest release.

**Comment by akyriako** [comment]
Hi @artem-lifshits, the latest release is populating the trace statuses. thanks for the quick fix!
