### ISSUE TITLE
ListTracesOpts.Limit upper and lower bound limits

### ISSUE THREAD

**Issue by akyriako** [opentelekomcloud/gophertelekomcloud#635]
**Package encountered the issue:**
[github.com/opentelekomcloud/gophertelekomcloud/openstack/cts/v2/traces](github.com/opentelekomcloud/gophertelekomcloud/openstack/cts/v2/traces)

**Description:**
`ListTracesOpts.Limit` as is stated in the [docs](https://pkg.go.dev/github.com/opentelekomcloud/gophertelekomcloud/openstack/cts/v2/traces@v0.9.1#ListTracesOpts) comes with a lower limit of 50 and upper limit of 200 traces.
`// Number of traces returned to the trace list. The default value is 50 and the maximum value is 200.`

However, if:
1. `ListTracesOpts.Limit` is **not** set, it returns always 10 and not the expected lower limit, assuming there are more than 50 traces available. 
2. `ListTracesOpts.Limit` is set to a value **over** 200, then the query returns 200+ traces without throwing an error. 
 
_Note_: Currently, there are **230** traces in my CTS Trace List; double checked from the console, and they were all returned in the result set when I set an upper limit of **250**.

**Expected behavior:**

1. The number of traces returned should fall within the range of predefined limits. 
2. If no limit is set, the result set should contain the predefined lower limit of traces, assuming there are more than the lower limit in CTS

**Additional notes:**
Assuming there are more traces, within the defined timespan of the query, than the upper limit; is there any way to fetch all the traces following a paging pattern like the one that OData follows?

**Comment by artem-lifshits** [comment]
Hello @akyriako. I've tested cts traces v2 via postman and gophertelekomcloud.
Both points you've described are not related to SDK, it's either documentation of API bug.

Here's response of these APIs by using postman:
1. `ListTracesOpts` without Limit
<img width="662" alt="Screenshot 2024-03-20 at 22 49 00" src="https://github.com/opentelekomcloud/gophertelekomcloud/assets/55093318/302d6f61-f8c3-4ef2-8542-df9b685bd2f3">

2.  `ListTracesOpts` Limit is set to a value over 200
<img width="726" alt="Screenshot 2024-03-20 at 22 50 30" src="https://github.com/opentelekomcloud/gophertelekomcloud/assets/55093318/d42c801b-86bd-4a72-a16f-ce40ed2d21b9">

**Comment by artem-lifshits** [comment]
To fetch next portion of traces you can call `List` function with `Next` parameter set to `Marker` response.
Here's an example:
```
	listOpts := traces.ListTracesOpts{
		To:   toMilliseconds,
		From: fromMilliseconds,
                Limit: "200",
	}
	for {
		list, err := traces.List(cv2, "system", listOpts)
		if err != nil {
			log.Fatal(err)
		}
		// do something with traces here

		if list.MetaData.Marker == "" {
			break
		}
		listOpts.Next = list.MetaData.Marker
	}
```

**Comment by akyriako** [comment]
Hi @artem-lifshits thanks for the paging tip worked fine, but I am not quite sure I get this one:
> Both points you've described are not related to SDK, it's either documentation of API bug.

- If it's just a documentation issue what are the actual default and upper limits?
- If it' an API bug, should I open a new issue? and if yes, where?

**Comment by artem-lifshits** [comment]
@akyriako since the behaviour of SDK and API are the same and differs from what is stated in docs - it's a bug.
I think it should be forwarded to QA team in order to check whether it's problem with API or outdated docs.

Ticket can be opened [here in bugmanagement project](https://jira.tsi-dev.otc-service.com/secure/CreateIssue!default.jspa).
