### ISSUE TITLE
Issue with clouds.yaml paths

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/gophertelekomcloud#75]
Our SDK tries to find `clouds.yaml` file only in `/etc/config/` and `~/.config/`. We need to have the possibility to configure path or something else.

 UPD:
We have issue with `./` path

**Comment by gtema** [comment]
Places must be as follows (order matters):
1) .
2) ~/.config/openstack
3) /etc/openstack

(https://opendev.org/openstack/openstacksdk/src/branch/master/openstack/config/loader.py#L49)

In addition to that in the same locations there might be clouds-public

**Comment by lego963** [comment]
yeap, we found issue with the first path, it was wrong
